import * as Location from "./locations";
import { RESOURCE_METADATA } from "./resourceMetadata";
import * as Resource from "./resources";
export const LOCATION_RESOURCES = {
    [Location.LOCATION_RED_RUSTLER_RENDEVOUS]: RESOURCE_METADATA[Resource.RESOURCE_COUNTERFEIT_CURRENCY],
    [Location.LOCATION_RED_ROCK_ROOST]: RESOURCE_METADATA[Resource.RESOURCE_WHISKEY],
    [Location.LOCATION_RED_RIVER_RANCH]: RESOURCE_METADATA[Resource.RESOURCE_CATTLE],
    [Location.LOCATION_REDSKIN_SACRED_POWWOW]: RESOURCE_METADATA[Resource.RESOURCE_BISON_HIDES],
    [Location.LOCATION_RED_CANYON_PASS]: RESOURCE_METADATA[Resource.RESOURCE_TREASURE]
};