import * as Location from "./locations";
export const LOCATION_NAMES = {
    [Location.LOCATION_TOWN_SQUARE]: "TOWN SQUARE",
    [Location.LOCATION_SILVER_STORE]: "SILVER STORE",
    [Location.LOCATION_RED_RUSTLER_RENDEVOUS]: "RED RUSTLER RENDEVOUS",
    [Location.LOCATION_RED_ROCK_ROOST]: "RED ROCK ROOST",
    [Location.LOCATION_RED_RIVER_RANCH]: "RED RIVER RANCH",
    [Location.LOCATION_REDSKIN_SACRED_POWWOW]: "REDSKIN SACRED POWWOW",
    [Location.LOCATION_RED_CANYON_PASS]: "RED CANYON PASS"
};